import type { Project, Block, TextBlock } from "@/types/content";
import { projects as registry } from "@/content/projects/_index";
import { projectImages, projectVideos } from "@/content/project-images";
import { structure } from "@/content/structure";

/**
 * The content/ folder tree decides where a project lives on the site:
 * its section folder sets the section, "selected works" membership + order
 * come from that folder, content/hidden (or no folder at all) unlists it,
 * and a folder's text.md replaces the page's body text. Folders with no
 * matching code file still get a page, synthesized from the folder itself.
 * The structure manifest is generated by scripts/scan-images.mjs.
 */
function applyStructure(p: Project): Project {
  const e = structure.entries[p.slug];
  // No folder in the tree: keep the page reachable but off every index.
  if (!e) return { ...p, unlisted: true };

  let blocks: Block[] = p.blocks;
  if (e.text && e.text.length > 0) {
    const texts: TextBlock[] = e.text.map((para, i) => ({
      kind: "text",
      lead: i === 0,
      paragraphs: [para],
    }));
    blocks = [...texts, ...p.blocks.filter((b) => b.kind !== "text")];
  }

  return {
    ...p,
    section: e.section ?? p.section,
    unlisted: e.hidden,
    blocks,
  };
}

/** Pages synthesized for tree folders that have no code file yet. */
function stubProjects(): Project[] {
  const known = new Set(registry.map((p) => p.slug));
  return Object.entries(structure.entries)
    .filter(([slug]) => !known.has(slug))
    .map(([slug, e]) => ({
      slug,
      title: e.title,
      section: e.section ?? "commissioned",
      year: String(new Date().getFullYear()),
      summary: e.text?.[0] ?? "",
      categories: [],
      blocks: [],
    }));
}

/**
 * Auto-associate a project with the media in its public/images/projects/<slug>/
 * and public/videos/projects/<slug>/ folders. Any file not already referenced
 * in the project (its `images` array or a video block) is appended to the
 * gallery, so dropping a photo or a converted .mp4 into a project's folder makes
 * it show up on that page without editing code. Explicit entries stay first and
 * win; images come before auto-added videos. The manifest is generated by
 * scripts/scan-images.mjs before every dev/build.
 */
function withAutoMedia(p: Project): Project {
  const autoImgs = projectImages[p.slug] ?? [];
  const autoVids = projectVideos[p.slug] ?? [];
  if (autoImgs.length === 0 && autoVids.length === 0) return p;

  const explicit = p.images ?? [];
  // Everything the project already shows, by path, so we never double it up.
  const have = new Set<string>();
  for (const im of explicit) {
    if (im.src) have.add(im.src);
    if (im.video) have.add(im.video);
  }
  for (const b of p.blocks) {
    if (b.kind === "video" && b.src) have.add(b.src);
  }

  const addImgs = autoImgs
    .filter((src) => !have.has(src))
    .map((src) => ({ src }));
  const addVids = autoVids
    .filter((src) => !have.has(src))
    .map((video) => ({ video }));
  if (addImgs.length === 0 && addVids.length === 0) return p;
  return { ...p, images: [...explicit, ...addImgs, ...addVids] };
}

/** Every project: code-defined ones plus pages synthesized from folders. */
function allSources(): Project[] {
  return [...registry, ...stubProjects()];
}

export function getAllProjects(): Project[] {
  return allSources()
    .map((p) => withAutoMedia(applyStructure(p)))
    .sort((a, b) => {
      // Sort newest year first; fall back to title.
      const ay = parseInt(a.year, 10) || 0;
      const by = parseInt(b.year, 10) || 0;
      if (by !== ay) return by - ay;
      return a.title.localeCompare(b.title);
    });
}

export function getListedProjects(): Project[] {
  return getAllProjects().filter((p) => !p.unlisted);
}

export function getProjectBySlug(slug: string): Project | undefined {
  const p = allSources().find((p) => p.slug === slug);
  return p ? withAutoMedia(applyStructure(p)) : undefined;
}

export function getAllProjectSlugs(): string[] {
  return allSources().map((p) => p.slug);
}

export function getProjectNeighbors(slug: string) {
  const list = getListedProjects();
  const i = list.findIndex((p) => p.slug === slug);
  if (i === -1) return { prev: undefined, next: undefined };
  const prev = list[(i - 1 + list.length) % list.length];
  const next = list[(i + 1) % list.length];
  return { prev, next };
}

/** Modifier class for a project's image-row size. "" = Small (default). */
export function imageSizeClass(size?: Project["imageSize"]): string {
  if (size === "L") return " size-l";
  if (size === "M") return " size-m";
  return "";
}

export function getCategories(): string[] {
  const set = new Set<string>();
  for (const p of getListedProjects()) {
    for (const c of p.categories) set.add(c);
  }
  return Array.from(set).sort();
}
