import type { Project } from "@/types/content";
import { projects as registry } from "@/content/projects/_index";
import { projectImages } from "@/content/project-images";

/**
 * Auto-associate a project with the images in its public/images/projects/<slug>/
 * folder. Any image file not already referenced in the project's own `images`
 * array is appended, so dropping a photo into a project's folder makes it show
 * up on that page without editing code. Explicit entries (captions, ordering,
 * video embeds) stay first and win. The manifest is generated by
 * scripts/scan-images.mjs before every dev/build.
 */
function withAutoImages(p: Project): Project {
  const auto = projectImages[p.slug];
  if (!auto || auto.length === 0) return p;
  const explicit = p.images ?? [];
  const have = new Set(explicit.map((im) => im.src).filter(Boolean));
  const appended = auto
    .filter((src) => !have.has(src))
    .map((src) => ({ src }));
  if (appended.length === 0) return p;
  return { ...p, images: [...explicit, ...appended] };
}

export function getAllProjects(): Project[] {
  return registry.map(withAutoImages).sort((a, b) => {
    // Sort newest year first; fall back to title.
    const ay = parseInt(a.year, 10) || 0;
    const by = parseInt(b.year, 10) || 0;
    if (by !== ay) return by - ay;
    return a.title.localeCompare(b.title);
  });
}

export function getListedProjects(): Project[] {
  return getAllProjects().filter((p) => !p.unlisted);
}

export function getProjectBySlug(slug: string): Project | undefined {
  const p = registry.find((p) => p.slug === slug);
  return p ? withAutoImages(p) : undefined;
}

export function getAllProjectSlugs(): string[] {
  return registry.map((p) => p.slug);
}

export function getProjectNeighbors(slug: string) {
  const list = getListedProjects();
  const i = list.findIndex((p) => p.slug === slug);
  if (i === -1) return { prev: undefined, next: undefined };
  const prev = list[(i - 1 + list.length) % list.length];
  const next = list[(i + 1) % list.length];
  return { prev, next };
}

/** Modifier class for a project's image-row size. "" = Small (default). */
export function imageSizeClass(size?: Project["imageSize"]): string {
  if (size === "L") return " size-l";
  if (size === "M") return " size-m";
  return "";
}

export function getCategories(): string[] {
  const set = new Set<string>();
  for (const p of getListedProjects()) {
    for (const c of p.categories) set.add(c);
  }
  return Array.from(set).sort();
}
