// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
export const projectImages: Record<string, string[]> = {
  "abstracted-organica": [
    "/images/projects/abstracted-organica/IMG_0013.JPEG",
    "/images/projects/abstracted-organica/TDMovieOut.6.jpeg",
    "/images/projects/abstracted-organica/TDMovieOut.121.jpeg"
  ],
  "atmos-norla-dome": [
    "/images/projects/atmos-norla-dome/01.jpg",
    "/images/projects/atmos-norla-dome/02.jpg",
    "/images/projects/atmos-norla-dome/IMG_1115.jpg"
  ],
  "autumn-contemplations": [
    "/images/projects/autumn-contemplations/hd.jpg",
    "/images/projects/autumn-contemplations/TREEPIC.3.jpg",
    "/images/projects/autumn-contemplations/TREEPIC.15.jpg"
  ],
  "cat-among-animals": [
    "/images/projects/cat-among-animals/01.jpg",
    "/images/projects/cat-among-animals/02.jpg",
    "/images/projects/cat-among-animals/03.jpg",
    "/images/projects/cat-among-animals/04.jpg",
    "/images/projects/cat-among-animals/05.jpg",
    "/images/projects/cat-among-animals/06.jpg",
    "/images/projects/cat-among-animals/IMG_5473.jpg",
    "/images/projects/cat-among-animals/IMG_5484.jpg"
  ],
  "cheahdx-purespace": [
    "/images/projects/cheahdx-purespace/IMG_0010.JPEG",
    "/images/projects/cheahdx-purespace/TDMovieOut.55.JPEG"
  ],
  "for-the-cause-25": [
    "/images/projects/for-the-cause-25/01.jpg"
  ],
  "for-the-cause-2026": [
    "/images/projects/for-the-cause-2026/IMG_1492.JPEG",
    "/images/projects/for-the-cause-2026/IMG_9507.JPEG"
  ],
  "forgotten-once-remembered": [
    "/images/projects/forgotten-once-remembered/01.jpg",
    "/images/projects/forgotten-once-remembered/02.jpg",
    "/images/projects/forgotten-once-remembered/03.jpg",
    "/images/projects/forgotten-once-remembered/04.jpg",
    "/images/projects/forgotten-once-remembered/05.jpg",
    "/images/projects/forgotten-once-remembered/IMG_9658.jpg"
  ],
  "hybrid-2-0": [
    "/images/projects/hybrid-2-0/DSC_8857.jpeg",
    "/images/projects/hybrid-2-0/IMG_6155.JPEG",
    "/images/projects/hybrid-2-0/IMG_6181.JPEG"
  ],
  "its-murph-weightless-tour": [
    "/images/projects/its-murph-weightless-tour/IMG_0334.JPEG",
    "/images/projects/its-murph-weightless-tour/IMG_0448.JPEG"
  ],
  "live-coding": [
    "/images/projects/live-coding/01.png",
    "/images/projects/live-coding/02.jpg",
    "/images/projects/live-coding/03.jpg",
    "/images/projects/live-coding/04.jpg",
    "/images/projects/live-coding/05.jpg",
    "/images/projects/live-coding/06.jpg"
  ],
  "mach1-festival": [
    "/images/projects/mach1-festival/01.jpg",
    "/images/projects/mach1-festival/02.jpg",
    "/images/projects/mach1-festival/03.jpg",
    "/images/projects/mach1-festival/DSCF0525.jpg",
    "/images/projects/mach1-festival/DSCF0719.jpg"
  ],
  "nike-air-liquid-max": [
    "/images/projects/nike-air-liquid-max/IMG_0125.JPEG"
  ],
  "nin-as-alive-as-you-need-me-to-be": [
    "/images/projects/nin-as-alive-as-you-need-me-to-be/01.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/02.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/03.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/04.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/05.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/06.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/07.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/08.jpg"
  ],
  "pitch-far-from-god": [
    "/images/projects/pitch-far-from-god/01.jpg",
    "/images/projects/pitch-far-from-god/02.jpg",
    "/images/projects/pitch-far-from-god/03.jpg"
  ],
  "the-xx-festival-tour": [
    "/images/projects/the-xx-festival-tour/IMG_0307.JPG",
    "/images/projects/the-xx-festival-tour/IMG_0336.JPG",
    "/images/projects/the-xx-festival-tour/IMG_0377.JPEG"
  ],
  "through-the-looking-glass-chadstone": [
    "/images/projects/through-the-looking-glass-chadstone/01.jpg",
    "/images/projects/through-the-looking-glass-chadstone/02.jpg",
    "/images/projects/through-the-looking-glass-chadstone/03.jpg"
  ]
};

export const projectVideos: Record<string, string[]> = {
  "a3-festival": [
    "/videos/projects/a3-festival/img-5261.mp4",
    "/videos/projects/a3-festival/img-5336.mp4",
    "/videos/projects/a3-festival/img-5439.mp4"
  ],
  "abstracted-organica": [
    "/videos/projects/abstracted-organica/img-9416.mp4",
    "/videos/projects/abstracted-organica/k-7.mp4",
    "/videos/projects/abstracted-organica/mach1-26.mp4",
    "/videos/projects/abstracted-organica/softnew-7.mp4",
    "/videos/projects/abstracted-organica/tdmovieout-25.mp4"
  ],
  "atmos-norla-dome": [
    "/videos/projects/atmos-norla-dome/03.mp4",
    "/videos/projects/atmos-norla-dome/img-1110.mp4",
    "/videos/projects/atmos-norla-dome/img-1123.mp4",
    "/videos/projects/atmos-norla-dome/img-1141.mp4"
  ],
  "autumn-contemplations": [
    "/videos/projects/autumn-contemplations/autumn-contemplations.mp4"
  ],
  "cat-among-animals": [
    "/videos/projects/cat-among-animals/01.mp4",
    "/videos/projects/cat-among-animals/03.mp4",
    "/videos/projects/cat-among-animals/tdmovieout-4-1.mp4",
    "/videos/projects/cat-among-animals/tdmovieout-7-1.mp4",
    "/videos/projects/cat-among-animals/visual1-render-1-1.mp4",
    "/videos/projects/cat-among-animals/visual1-render-2025-12-05-12-26-35.mp4"
  ],
  "cheahdx-purespace": [
    "/videos/projects/cheahdx-purespace/tdmovieout-81.mp4",
    "/videos/projects/cheahdx-purespace/tdmovieout-92.mp4"
  ],
  "for-the-cause-25": [
    "/videos/projects/for-the-cause-25/01.mp4",
    "/videos/projects/for-the-cause-25/02.mp4",
    "/videos/projects/for-the-cause-25/05.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-37-2.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-41-1.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-42-1.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-45-1.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-63-1.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-64.mp4",
    "/videos/projects/for-the-cause-25/tdmovieout-69-1.mp4"
  ],
  "for-the-cause-2026": [
    "/videos/projects/for-the-cause-2026/ftc-30.mp4",
    "/videos/projects/for-the-cause-2026/img-1522.mp4",
    "/videos/projects/for-the-cause-2026/img-9585.mp4",
    "/videos/projects/for-the-cause-2026/img-9624.mp4",
    "/videos/projects/for-the-cause-2026/img-9632.mp4",
    "/videos/projects/for-the-cause-2026/img-9637.mp4",
    "/videos/projects/for-the-cause-2026/img-9653.mp4",
    "/videos/projects/for-the-cause-2026/img-9654.mp4"
  ],
  "forgotten-once-remembered": [
    "/videos/projects/forgotten-once-remembered/01.mp4",
    "/videos/projects/forgotten-once-remembered/blue-ice.mp4"
  ],
  "hybrid-2-0": [
    "/videos/projects/hybrid-2-0/c8200.mp4",
    "/videos/projects/hybrid-2-0/img-6185.mp4",
    "/videos/projects/hybrid-2-0/img-6191.mp4",
    "/videos/projects/hybrid-2-0/img-6277.mp4",
    "/videos/projects/hybrid-2-0/tdmovieout-8.mp4",
    "/videos/projects/hybrid-2-0/tdmovieout-16.mp4"
  ],
  "its-murph-weightless-tour": [
    "/videos/projects/its-murph-weightless-tour/hd-20abstract-7-mov.mp4",
    "/videos/projects/its-murph-weightless-tour/murphv2.mp4",
    "/videos/projects/its-murph-weightless-tour/tdmovieout-10-mov.mp4"
  ],
  "live-coding": [
    "/videos/projects/live-coding/01.mp4",
    "/videos/projects/live-coding/02.mp4",
    "/videos/projects/live-coding/03.mp4",
    "/videos/projects/live-coding/04.mp4",
    "/videos/projects/live-coding/aqoeznfi2cwlstvwbeq-ppvs5kurfvjzh9lwosijsjo2.mp4",
    "/videos/projects/live-coding/img-2225-2.mp4",
    "/videos/projects/live-coding/img-4095.mp4",
    "/videos/projects/live-coding/untitled.mp4"
  ],
  "mach1-festival": [
    "/videos/projects/mach1-festival/img-9038.mp4",
    "/videos/projects/mach1-festival/img-9045.mp4",
    "/videos/projects/mach1-festival/img-9060.mp4",
    "/videos/projects/mach1-festival/tdmovieout-25.mp4"
  ],
  "nike-air-liquid-max": [
    "/videos/projects/nike-air-liquid-max/appear-8-mov.mp4",
    "/videos/projects/nike-air-liquid-max/appear-33-mov.mp4",
    "/videos/projects/nike-air-liquid-max/appear-38-mov.mp4",
    "/videos/projects/nike-air-liquid-max/appear-67-mov.mp4",
    "/videos/projects/nike-air-liquid-max/copy-9b0c5501-1b50-4c21-9bc3-7b03d2453258.mp4"
  ],
  "nin-as-alive-as-you-need-me-to-be": [
    "/videos/projects/nin-as-alive-as-you-need-me-to-be/01.mp4",
    "/videos/projects/nin-as-alive-as-you-need-me-to-be/new-clip.mp4"
  ],
  "pitch-far-from-god": [
    "/videos/projects/pitch-far-from-god/img-3357.mp4",
    "/videos/projects/pitch-far-from-god/tdmovieout-57.mp4",
    "/videos/projects/pitch-far-from-god/trimmed-stars-2.mp4"
  ],
  "smokedope2016-2016lyfe": [
    "/videos/projects/smokedope2016-2016lyfe/01.mp4",
    "/videos/projects/smokedope2016-2016lyfe/02.mp4",
    "/videos/projects/smokedope2016-2016lyfe/03.mp4",
    "/videos/projects/smokedope2016-2016lyfe/04.mp4",
    "/videos/projects/smokedope2016-2016lyfe/05.mp4",
    "/videos/projects/smokedope2016-2016lyfe/tdmovieout-99-1.mp4",
    "/videos/projects/smokedope2016-2016lyfe/tdmovieout-114.mp4",
    "/videos/projects/smokedope2016-2016lyfe/tdmovieout-121.mp4",
    "/videos/projects/smokedope2016-2016lyfe/tdmovieout-139.mp4"
  ],
  "the-xx-festival-tour": [
    "/videos/projects/the-xx-festival-tour/coachella-weekend-1-full-show.mp4",
    "/videos/projects/the-xx-festival-tour/islands-20v1-7-mov.mp4",
    "/videos/projects/the-xx-festival-tour/snapinsta-to-aqnqka4ufybsasdn3tftrg9gb-kacno.mp4",
    "/videos/projects/the-xx-festival-tour/snapinsta-to-aqoe0f9ns6dsnv27gq8muojf7j-vjjp.mp4"
  ],
  "thread-congee-club": [
    "/videos/projects/thread-congee-club/4e2e4a523fc740ceadcf44db3e3d70cc.mp4",
    "/videos/projects/thread-congee-club/img-5879.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-39-1.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-61.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-82-1.mp4"
  ],
  "through-the-looking-glass-chadstone": [
    "/videos/projects/through-the-looking-glass-chadstone/chadstone-light.mp4"
  ],
  "woven-touch": [
    "/videos/projects/woven-touch/thread-19.mp4"
  ]
};

export const toolImages: Record<string, string[]> = {};
