// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
export const projectImages: Record<string, string[]> = {
  "atmos-norla-dome": [
    "/images/projects/atmos-norla-dome/01.jpg",
    "/images/projects/atmos-norla-dome/02.jpg",
    "/images/projects/atmos-norla-dome/IMG_1115.jpg"
  ],
  "cat-among-animals": [
    "/images/projects/cat-among-animals/01.jpg",
    "/images/projects/cat-among-animals/02.jpg",
    "/images/projects/cat-among-animals/03.jpg",
    "/images/projects/cat-among-animals/04.jpg",
    "/images/projects/cat-among-animals/05.jpg",
    "/images/projects/cat-among-animals/06.jpg",
    "/images/projects/cat-among-animals/IMG_5473.jpg",
    "/images/projects/cat-among-animals/IMG_5484.jpg"
  ],
  "for-the-cause": [
    "/images/projects/for-the-cause/01.jpg"
  ],
  "forgotten-once-remembered": [
    "/images/projects/forgotten-once-remembered/01.jpg",
    "/images/projects/forgotten-once-remembered/02.jpg",
    "/images/projects/forgotten-once-remembered/03.jpg",
    "/images/projects/forgotten-once-remembered/04.jpg",
    "/images/projects/forgotten-once-remembered/05.jpg"
  ],
  "live-coding": [
    "/images/projects/live-coding/01.png",
    "/images/projects/live-coding/02.jpg",
    "/images/projects/live-coding/03.jpg",
    "/images/projects/live-coding/04.jpg",
    "/images/projects/live-coding/05.jpg",
    "/images/projects/live-coding/06.jpg"
  ],
  "mach1-festival": [
    "/images/projects/mach1-festival/01.jpg",
    "/images/projects/mach1-festival/02.jpg",
    "/images/projects/mach1-festival/03.jpg"
  ],
  "nin-as-alive-as-you-need-me-to-be": [
    "/images/projects/nin-as-alive-as-you-need-me-to-be/01.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/02.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/03.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/04.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/05.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/06.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/07.jpg",
    "/images/projects/nin-as-alive-as-you-need-me-to-be/08.jpg"
  ],
  "pitch-far-from-god": [
    "/images/projects/pitch-far-from-god/01.jpg",
    "/images/projects/pitch-far-from-god/02.jpg",
    "/images/projects/pitch-far-from-god/03.jpg"
  ]
};

export const projectVideos: Record<string, string[]> = {
  "atmos-norla-dome": [
    "/videos/projects/atmos-norla-dome/03.mp4",
    "/videos/projects/atmos-norla-dome/img-1110.mp4",
    "/videos/projects/atmos-norla-dome/img-1123.mp4",
    "/videos/projects/atmos-norla-dome/img-1141.mp4"
  ],
  "cat-among-animals": [
    "/videos/projects/cat-among-animals/tdmovieout-4-1.mp4",
    "/videos/projects/cat-among-animals/tdmovieout-7-1.mp4",
    "/videos/projects/cat-among-animals/visual1-render-1-1.mp4",
    "/videos/projects/cat-among-animals/visual1-render-2025-12-05-12-26-35.mp4"
  ],
  "for-the-cause": [
    "/videos/projects/for-the-cause/tdmovieout-37-2.mp4",
    "/videos/projects/for-the-cause/tdmovieout-41-1.mp4",
    "/videos/projects/for-the-cause/tdmovieout-42-1.mp4",
    "/videos/projects/for-the-cause/tdmovieout-45-1.mp4",
    "/videos/projects/for-the-cause/tdmovieout-63-1.mp4",
    "/videos/projects/for-the-cause/tdmovieout-64.mp4",
    "/videos/projects/for-the-cause/tdmovieout-69-1.mp4"
  ],
  "live-coding": [
    "/videos/projects/live-coding/04.mp4",
    "/videos/projects/live-coding/aqoeznfi2cwlstvwbeq-ppvs5kurfvjzh9lwosijsjo2.mp4",
    "/videos/projects/live-coding/img-2225-2.mp4",
    "/videos/projects/live-coding/img-4095.mp4",
    "/videos/projects/live-coding/untitled.mp4"
  ],
  "nin-as-alive-as-you-need-me-to-be": [
    "/videos/projects/nin-as-alive-as-you-need-me-to-be/01.mp4",
    "/videos/projects/nin-as-alive-as-you-need-me-to-be/new-clip.mp4"
  ],
  "pitch-far-from-god": [
    "/videos/projects/pitch-far-from-god/img-3357.mp4",
    "/videos/projects/pitch-far-from-god/tdmovieout-57.mp4",
    "/videos/projects/pitch-far-from-god/trimmed-stars-2.mp4"
  ],
  "thread-congee-club": [
    "/videos/projects/thread-congee-club/4e2e4a523fc740ceadcf44db3e3d70cc.mp4",
    "/videos/projects/thread-congee-club/img-5879.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-39-1.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-61.mp4",
    "/videos/projects/thread-congee-club/tdmovieout-82-1.mp4"
  ]
};
