// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
// Derived from the content/ folder tree; see that folder to reorganize the site.
export interface StructureEntry {
  /** Section from the folder's location; null = keep the code-defined one. */
  section: "commissioned" | "installation" | "sketch" | null;
  /** In content/hidden: page exists but is left off the index. */
  hidden: boolean;
  /** Fallback page title (from the folder name) for folders with no code file. */
  title: string;
  /** Paragraphs from the folder's text.md, replacing the page's body text. */
  text: string[] | null;
}

export const structure: {
  /** Selected Works slugs, in folder-name order. */
  selected: string[];
  entries: Record<string, StructureEntry>;
} = {
  "selected": [
    "the-xx-festival-tour",
    "hybrid-2-0",
    "nin-as-alive-as-you-need-me-to-be",
    "its-murph-weightless-tour",
    "a3-festival",
    "nike-air-liquid-max",
    "abstracted-organica",
    "for-the-cause-2026",
    "through-the-looking-glass-chadstone"
  ],
  "entries": {
    "cheahdx-purespace": {
      "section": "commissioned",
      "hidden": false,
      "title": "Cheahdx Purespace",
      "text": null
    },
    "for-the-cause-25": {
      "section": "commissioned",
      "hidden": false,
      "title": "For The Cause 25",
      "text": null
    },
    "odetari-dont-die": {
      "section": "commissioned",
      "hidden": false,
      "title": "Odetari Dont Die",
      "text": null
    },
    "ravyn-lenae-sips-and-sounds": {
      "section": "commissioned",
      "hidden": false,
      "title": "Ravyn Lenae Sips And Sounds",
      "text": null
    },
    "smokedope2016-2016lyfe": {
      "section": "commissioned",
      "hidden": false,
      "title": "Smokedope2016 2016lyfe",
      "text": null
    },
    "atmos-norla-dome": {
      "section": "installation",
      "hidden": false,
      "title": "Atmos Norla Dome",
      "text": null
    },
    "cat-among-animals": {
      "section": "installation",
      "hidden": false,
      "title": "Cat Among Animals",
      "text": null
    },
    "forgotten-once-remembered": {
      "section": "installation",
      "hidden": false,
      "title": "Forgotten Once Remembered",
      "text": null
    },
    "handclap-album-launch": {
      "section": "installation",
      "hidden": false,
      "title": "Handclap Album Launch",
      "text": null
    },
    "live-coding": {
      "section": "installation",
      "hidden": false,
      "title": "Live Coding",
      "text": null
    },
    "mach1-festival": {
      "section": "installation",
      "hidden": false,
      "title": "Mach1 Festival",
      "text": null
    },
    "nu-saul-williams": {
      "section": "installation",
      "hidden": false,
      "title": "Nu Saul Williams",
      "text": null
    },
    "pitch-far-from-god": {
      "section": "installation",
      "hidden": false,
      "title": "Pitch Far From God",
      "text": null
    },
    "thread-congee-club": {
      "section": "installation",
      "hidden": false,
      "title": "Thread Congee Club",
      "text": null
    },
    "autumn-contemplations": {
      "section": "sketch",
      "hidden": false,
      "title": "Autumn Contemplations",
      "text": null
    },
    "woven-touch": {
      "section": "sketch",
      "hidden": false,
      "title": "Woven Touch",
      "text": null
    },
    "the-xx-festival-tour": {
      "section": null,
      "hidden": false,
      "title": "The Xx Festival Tour",
      "text": null
    },
    "hybrid-2-0": {
      "section": null,
      "hidden": false,
      "title": "Hybrid 2 0",
      "text": null
    },
    "nin-as-alive-as-you-need-me-to-be": {
      "section": null,
      "hidden": false,
      "title": "Nin As Alive As You Need Me To Be",
      "text": null
    },
    "its-murph-weightless-tour": {
      "section": null,
      "hidden": false,
      "title": "Its Murph Weightless Tour",
      "text": null
    },
    "a3-festival": {
      "section": null,
      "hidden": false,
      "title": "A3 Festival",
      "text": null
    },
    "nike-air-liquid-max": {
      "section": null,
      "hidden": false,
      "title": "Nike Air Liquid Max",
      "text": null
    },
    "abstracted-organica": {
      "section": null,
      "hidden": false,
      "title": "Abstracted Organica",
      "text": null
    },
    "for-the-cause-2026": {
      "section": null,
      "hidden": false,
      "title": "For The Cause 2026",
      "text": null
    },
    "through-the-looking-glass-chadstone": {
      "section": null,
      "hidden": false,
      "title": "Through The Looking Glass Chadstone",
      "text": null
    }
  }
};
