#!/usr/bin/env node
/**
 * Auto-associate images with project pages.
 *
 * Scans every public/images/projects/<slug>/ folder and writes a manifest
 * mapping each slug to its image files (natural-sorted: 01, 02, 10 …). Each
 * project appends these to its gallery automatically (see src/lib/projects.ts),
 * so dropping an image into a project's folder makes it show up on that page,
 * with no code changes.
 *
 *   node scripts/scan-images.mjs      (or: npm run scan-images)
 *
 * Runs automatically before `npm run dev` and `npm run build`.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const imagesRoot = resolve(root, "public/images/projects");
const outFile = resolve(root, "src/content/project-images.ts");

const IMAGE_RE = /\.(jpe?g|png|webp|gif|avif)$/i;

/** @type {Record<string, string[]>} */
const manifest = {};

let slugs = [];
try {
  slugs = readdirSync(imagesRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
} catch {
  // public/images/projects doesn't exist yet — write an empty manifest.
}

for (const slug of slugs) {
  let files = [];
  try {
    files = readdirSync(resolve(imagesRoot, slug)).filter(
      (f) => IMAGE_RE.test(f) && !f.startsWith("."),
    );
  } catch {
    continue;
  }
  if (files.length === 0) continue;
  // Natural sort so 01, 02, 10 order correctly regardless of zero-padding.
  files.sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }),
  );
  manifest[slug] = files.map((f) => `/images/projects/${slug}/${f}`);
}

const body = `// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
// Maps each project slug to the image files in public/images/projects/<slug>/.
// Regenerated before every dev/build; run \`npm run scan-images\` to refresh.
export const projectImages: Record<string, string[]> = ${JSON.stringify(
  manifest,
  null,
  2,
)};
`;

writeFileSync(outFile, body);
const n = Object.keys(manifest).length;
const total = Object.values(manifest).reduce((s, a) => s + a.length, 0);
console.log(
  `scan-images: ${total} image${total === 1 ? "" : "s"} across ${n} project folder${n === 1 ? "" : "s"} → src/content/project-images.ts`,
);
