#!/usr/bin/env node
/**
 * Auto-associate media with project pages.
 *
 * Scans public/images/projects/<slug>/ for image files and
 * public/videos/projects/<slug>/ for web-ready video files, then writes a
 * manifest mapping each slug to them (natural-sorted). Each project appends
 * these to its gallery automatically (see src/lib/projects.ts), so dropping a
 * photo (or a converted .mp4) into a project's folder makes it appear, with no
 * code changes.
 *
 *   node scripts/scan-images.mjs      (or: npm run scan-images)
 *
 * Runs automatically before `npm run dev` and `npm run build`.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const outFile = resolve(root, "src/content/project-images.ts");

const IMAGE_RE = /\.(jpe?g|png|webp|gif|avif)$/i;
const VIDEO_RE = /\.(mp4|webm)$/i;

/** Map each slug folder under `base` to the matching files, as web paths. */
function scan(base, re, urlBase) {
  const out = {};
  let slugs = [];
  try {
    slugs = readdirSync(resolve(root, base), { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
  } catch {
    return out;
  }
  for (const slug of slugs) {
    let files = [];
    try {
      files = readdirSync(resolve(root, base, slug)).filter(
        (f) => re.test(f) && !f.startsWith("."),
      );
    } catch {
      continue;
    }
    if (files.length === 0) continue;
    files.sort((a, b) =>
      a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }),
    );
    out[slug] = files.map((f) => `${urlBase}/${slug}/${f}`);
  }
  return out;
}

const images = scan("public/images/projects", IMAGE_RE, "/images/projects");
const videos = scan("public/videos/projects", VIDEO_RE, "/videos/projects");

const body = `// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
// Maps each project slug to the media files found under
// public/images/projects/<slug>/ and public/videos/projects/<slug>/.
// Regenerated before every dev/build; run \`npm run scan-images\` to refresh.
export const projectImages: Record<string, string[]> = ${JSON.stringify(images, null, 2)};

export const projectVideos: Record<string, string[]> = ${JSON.stringify(videos, null, 2)};
`;

writeFileSync(outFile, body);
const ni = Object.values(images).reduce((s, a) => s + a.length, 0);
const nv = Object.values(videos).reduce((s, a) => s + a.length, 0);
console.log(
  `scan-images: ${ni} images + ${nv} videos across ${Object.keys(images).length}/${Object.keys(videos).length} folders → src/content/project-images.ts`,
);
